98_live_practice_django/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

98_live_practice_django/inmoongram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

98_live_practice_django/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100)
    content = models.CharField(max_length=250)
    image = models.ImageField(blank=True)
    image_description = models.TextField()
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add = True)

98_live_practice_django/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

98_live_practice_django/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

98_live_practice_django/articles/templates/articles/create.html
{% extends "base.html" %}

{% block content %}
<h1>게시글 생성 페이지</h1>
<form action="{% url "articles:create" %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="CREATE">
</form>
<a href="{% url "articles:index" %}">[BACK]</a>
{% endblock content %}

98_live_practice_django/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}
<h1>게시글 상세 페이지</h1>
<p>{{article.pk}}번 게시글 | {{article.title}}</p>
<p>작성 시간 : {{article.created_at}}</p>
<hr>
{% if article.image %}
  <img src="{{article.image.url}}" alt="img">
{% endif %}
<p>{{article.content}}</p>
<hr>
<a href="{% url "articles:update" article.pk %}">[UPDATE]</a>
<form action="{% url "articles:delete" article.pk %}" method="post">
  {% csrf_token %}
  <input type="submit" value="DELETE">
</form>
<a href="{% url "articles:index" %}">[BACK]</a>
{% endblock content %}

98_live_practice_django/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
<h1>나만의 SNS 서비스</h1>
<a href="{% url "articles:create" %}">[CREATE]</a>
<div style="margin-left:30px">
  {% for article in articles %}
    {% if article.image %}
      <p><img src="{{article.image.url}}" alt="img"></p>
    {% endif %}
    <p><a href="{% url "articles:detail" article.pk %}">{{article.title}}</a></p>
    <hr>
  {% endfor %}
</div>
{% endblock content %}

98_live_practice_django/articles/templates/articles/update.html
{% extends "base.html" %}

{% block content %}
<h1>게시글 수정 페이지</h1>
<form action="{% url "articles:update" article.pk %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="UPDATE">
</form>
<a href="{% url "articles:index" %}">[BACK]</a>
{% endblock content %}