05_django/03_db_04/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/update/', views.superuser_update, name='superuser_update'),
    path('<int:user_pk>/delete/', views.delete, name='delete'),
]

05_django/03_db_04/convenience_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('stores/', include('stores.urls')),
]

05_django/03_db_04/stores/urls.py
from django.urls import path
from . import views


app_name = 'stores'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:store_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:store_pk>/create_product/', views.create_product, name='create_product'),
    path('<int:store_pk>/<int:product_pk>/delete_product', views.delete_product, name='delete_product'),
]

05_django/03_db_04/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    pass

05_django/03_db_04/stores/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Store(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    is_franchise = models.BooleanField()

class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    amount = models.IntegerField()
    price = models.IntegerField()
    adult = models.BooleanField()

05_django/03_db_04/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username',)


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name',)


class SuperuserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('is_staff',)

05_django/03_db_04/stores/forms.py
from django import forms
from .models import Store, Product


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = '__all__'

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'amount', 'price', 'adult',)

05_django/03_db_04/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm, CustomUserChangeForm, SuperuserChangeForm


User = get_user_model()
# Create your views here.
def index(request):
    users = User.objects.all()
    context = {
        'users': users,
    }
    return render(request, 'accounts/index.html', context)
    
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('stores:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('stores:index')
    else:
        form = AuthenticationForm(request)
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('stores:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)

def superuser_update(request, user_pk):
    person = User.objects.get(pk=user_pk)
    if request.method == 'POST':
        form = SuperuserChangeForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = SuperuserChangeForm(instance=person)
    context = {
        'form': form,
    }
    return render(request, 'accounts/superuser_update.html', context)

def delete(request, user_pk):
    person = User.objects.get(pk=user_pk)
    person.delete()
    return redirect('accounts:index')

05_django/03_db_04/stores/views.py
from django.shortcuts import render, redirect
from .models import Store, Product
from .forms import StoreForm, ProductForm

# Create your views here.
def index(request):
    stores = Store.objects.all()
    context = {
        'stores': stores,
    }
    return render(request, 'stores/index.html', context)

def detail(request, store_pk):
    store = Store.objects.get(pk=store_pk)
    product_form = ProductForm()
    products = Product.objects.filter(store=store)
    context = {
        'store': store,
        'product_form': product_form,
        'products': products,
    }
    return render(request, 'stores/detail.html', context)

def create(request):
    if request.method == 'POST':
        form = StoreForm(request.POST)
        if form.is_valid():
            store = form.save()
            return redirect('stores:detail', store.pk)
    else:
        form = StoreForm()
    context = {
        'form': form,
    }
    return render(request, 'stores/create.html', context)

def create_product(request, store_pk):
    store = Store.objects.get(pk=store_pk)
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.store = store
            product.save()
            return redirect('stores:detail', store_pk)
        
def delete_product(request, store_pk, product_pk):
    product = Product.objects.get(pk=product_pk)
    product.delete()
    return redirect('stores:detail', store_pk)

05_django/03_db_04/accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block content %}
  <h1>직원 전체 목록</h1>
  <ul>
    {% for one in users %}
      <li>이름 : {{one.username}}</li>
      <li>admin 여부 : {{one.is_superuser}}</li>
      <li>staff 여부 : {{one.is_staff}}</li>
      {% if user == one %}
        <a href="{% url "accounts:update" %}">회원 정보 수정</a>
      {% endif %}
      {% if user.is_superuser %}
        <a href="{% url "accounts:superuser_update" one.pk %}">관리자 여부 수정</a>
        <form action="{% url "accounts:delete" one.pk %}" method="post">
          {% csrf_token %}
          <input type="submit" value="회원 삭제">
        </form>
      {% endif %}
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}

05_django/03_db_04/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <h1>LOGIN Page</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="LOGIN">
  </form>
{% endblock content %}

05_django/03_db_04/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
  <h1>Sign Up Page</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Sign up">
  </form>
{% endblock content %}

05_django/03_db_04/accounts/templates/accounts/superuser_update.html
{% extends "base.html" %}

{% block content %}
  <h1>관리자 여부 수정</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정">
  </form>
{% endblock content %}

05_django/03_db_04/accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
  <h1>회원 정보 수정</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정">
  </form>
{% endblock content %}

05_django/03_db_04/stores/templates/stores/create.html
{% extends "base.html" %}

{% block content %}
  <h1>신규 매장 등록 페이지</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="등록">
  </form>
  <a href="{% url "stores:index" %}">[돌아가기]</a>
{% endblock content %}

05_django/03_db_04/stores/templates/stores/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>편의점 상세 정보</h1>
  <p>점장 : {{store.user.username}}</p>
  <p>주소 : {{store.address}}</p>
  <p>체인점 여부 : {{store.is_franchise}}</p>
  <hr>
  {% if user.is_superuser %}
    <h3>신규 상품 등록</h3>
    <form action="{% url "stores:create_product" store.pk %}" method="post">
      {% csrf_token %}
      {{product_form.as_p}}
      <input type="submit" value="물품 등록">
    </form>
    <hr>
  {% endif %}
  <h3>전체 상품 목록</h3>
  <ul>
    {% for product in products %}
      <li>이름 : {{product.name}}</li>
      <li>가격 : {{product.price}}</li>
      {% if user == product.user %}
        <form action="{% url "stores:delete_product" store.pk product.pk %}" method="post">
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
      {% endif %}
    {% endfor %}
  </ul>
  <a href="{% url "stores:index" %}">[전체 목록 보기]</a>
{% endblock content %}

05_django/03_db_04/stores/templates/stores/index.html
{% extends "base.html" %}

{% block content %}
  <h1>전체 편의점 목록</h1>
  <a href="{% url "stores:create" %}">[신규 매장 등록]</a>
  <ul>
    {% for store in stores %}
      <a href="{% url "stores:detail" store.pk %}">
        <li>점장 : {{store.user.username}}</li>
        <li>주소 : {{store.address}}</li>
      </a>
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}

05_django/03_db_04/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% if user.is_authenticated %}
    <h3>반갑습니다. {{user.username}}님!</h3>
    <form action="{% url "accounts:logout" %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Logout">
    </form>
    {% if user.is_staff %}
      <a href="{% url "accounts:index" %}">[전체 직원 목록]</a>
    {% endif %}
    <a href="{% url "stores:index" %}">[전체 매장 목록]</a>
  {% else %}
    <h3>로그인 해 주세요.</h3>
    <a href="{% url "accounts:login" %}">[Login]</a>
    <a href="{% url "accounts:signup" %}">[Sign Up]</a>
  {% endif %}
  {% block content %}
  {% endblock content %}
</body>
</html>